# Generated by Django 5.0.3 on 2024-03-06 04:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fname', models.CharField(max_length=50, verbose_name='First Name')),
                ('user_lname', models.CharField(max_length=50, verbose_name='Last Name')),
                ('user_email', models.EmailField(max_length=200, unique=True, verbose_name="User's Email")),
                ('user_position', models.CharField(max_length=200, verbose_name='Position')),
                ('pub_date', models.DateField(default=datetime.datetime(2024, 3, 6, 4, 23, 32, 498066, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
