# Generated by Django 5.0.3 on 2024-03-06 08:17

import datetime
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='profile_pic/image.jpg', upload_to=users.models.image_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 3, 6, 8, 17, 26, 453755, tzinfo=datetime.timezone.utc)),
        ),
    ]
